// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBONyVQEQ3_avmLLEmkvMmT3T52A0DbnWw',
    appId: '1:765340712532:web:e3c74494c317f884fd77c1',
    messagingSenderId: '765340712532',
    projectId: 'village-bus-tracker',
    authDomain: 'village-bus-tracker.firebaseapp.com',
    databaseURL: 'https://village-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'village-bus-tracker.firebasestorage.app',
    measurementId: 'G-L5X0YHWC7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo_IoZnr8YaAJ5shjwmhRcUxmlymxWwJA',
    appId: '1:765340712532:android:f1a27b61de1030c9fd77c1',
    messagingSenderId: '765340712532',
    projectId: 'village-bus-tracker',
    databaseURL: 'https://village-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'village-bus-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHm5i5fshIRYu2b2RfIXfthSB4Uz9IDI',
    appId: '1:765340712532:ios:dbf25ad725644ba7fd77c1',
    messagingSenderId: '765340712532',
    projectId: 'village-bus-tracker',
    databaseURL: 'https://village-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'village-bus-tracker.firebasestorage.app',
    iosBundleId: 'com.example.villageBusTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXHm5i5fshIRYu2b2RfIXfthSB4Uz9IDI',
    appId: '1:765340712532:ios:dbf25ad725644ba7fd77c1',
    messagingSenderId: '765340712532',
    projectId: 'village-bus-tracker',
    databaseURL: 'https://village-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'village-bus-tracker.firebasestorage.app',
    iosBundleId: 'com.example.villageBusTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBONyVQEQ3_avmLLEmkvMmT3T52A0DbnWw',
    appId: '1:765340712532:web:5f097f8590cdd654fd77c1',
    messagingSenderId: '765340712532',
    projectId: 'village-bus-tracker',
    authDomain: 'village-bus-tracker.firebaseapp.com',
    databaseURL: 'https://village-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'village-bus-tracker.firebasestorage.app',
    measurementId: 'G-RDVHWTND97',
  );
}
